### ISSUE TITLE
Failed to upload test assets, error: failed to start test: 403, error: {"error":"Unauthorized request"}

### ISSUE THREAD

**Issue by DanielJette** [bitrise-steplib/steps-virtual-device-testing-for-android#73] opened 2021-05-12 15:24 UTC
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.1.4
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)?  NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

All our Virtual Device Testing for Android steps are failing with 403:

`Failed to upload test assets, error: failed to start test: 403, error: {"error":"Unauthorized request"}`

```
Uploading app and test files
App path (/bitrise/deploy/Neo.internal-debug-2021.8.apk), is bundle: false
Assets requested: {isBundle:false testApp:<nil> Apk:{UploadURL: GcsPath: Filename:Neo.internal-debug-2021.8.apk} Aab:{UploadURL: GcsPath: Filename:} TestApk:{UploadURL: GcsPath: Filename:app-internal-debug-androidTest.apk} RoboScript:{UploadURL: GcsPath: Filename:} ObbFiles:[]}
Failed to upload test assets, error: failed to start test: 403, error: {"error":"Unauthorized request"}
```

### Bitrise info

- Build URL: https://app.bitrise.io/build/801e745af834b252#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log:

<details>
  <pre>
+------------------------------------------------------------------------------+

| (4) virtual-device-testing-for-android@1                                     |
+------------------------------------------------------------------------------+
| id: virtual-device-testing-for-android                                       |
| version: 1.1.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-05-12T15:16:32Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- AppPath: /bitrise/deploy/Neo.internal-debug-2021.8.apk
- TestTimeout: 3000.000000
- FlakyTestAttempts: 0
- DownloadTestResults: true
- DirectoriesToPull: /storage/emulated/0/Android/data/com.neofinancial.neo.debug/files/testify_images/
- AutoGoogleLogin: false
- EnvironmentVariables: TESTIFY_USE_SDCARD=true
useSdCard=true
- ObbFilesList: 
- TestDevices:
---
Model    API Level   Locale   Orientation   
Pixel2   29          en_US    portrait      
---
- TestType: robo
- RoboInitialActivity: 
- RoboScenarioFile: 
- RoboDirectives: 
- RoboMaxDepth: 
- RoboMaxSteps: 
Uploading app and test files
App path (/bitrise/deploy/Neo.internal-debug-2021.8.apk), is bundle: false
Assets requested: {isBundle:false testApp:<nil> Apk:{UploadURL: GcsPath: Filename:Neo.internal-debug-2021.8.apk} Aab:{UploadURL: GcsPath: Filename:} TestApk:{UploadURL: GcsPath: Filename:} RoboScript:{UploadURL: GcsPath: Filename:} ObbFiles:[]}
Failed to upload test assets, error: failed to start test: 403, error: {"error":"Unauthorized request"}
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | virtual-device-testing-for-android@1 (exit code: 1)           | 9.46 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...se-steplib/steps-virtual-device-testing-for-android/issues |
| Source: ...thub.com/bitrise-steplib/steps-virtual-device-testing-for-android |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by ofalvai** [comment] 2021-05-12 16:33
Hey @DanielJette, thanks for the report! We have found the root cause and deployed the fix, it should be working now. Please try re-running the failed build.

**Comment by DanielJette** [comment] 2021-05-12 17:35
Hi @ofalvai Unfortunately the same error appears on a re-run triggered on 2021.05.12 @ 13:15

https://app.bitrise.io/build/aec9fb3795aac4fe#?tab=log

```
+------------------------------------------------------------------------------+

| (3) Testify UI Testing                                                       |
+------------------------------------------------------------------------------+
| id: virtual-device-testing-for-android                                       |
| version: 1.1.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-05-12T17:29:37Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- AppPath: /bitrise/deploy/Neo.internal-debug-2021.8.apk
- TestTimeout: 3000.000000
- FlakyTestAttempts: 3
- DownloadTestResults: true
- DirectoriesToPull: /storage/emulated/0/Android/data/com.neofinancial.neo.debug/files/testify_images/
- AutoGoogleLogin: false
- EnvironmentVariables: TESTIFY_USE_SDCARD=true
useSdCard=true
- ObbFilesList: 
- TestDevices:
---
Model    API Level   Locale   Orientation   
Pixel2   29          en_US    portrait      
---
- TestType: instrumentation
- TestApkPath: /bitrise/deploy/app-internal-debug-androidTest.apk
- InstTestPackageID: 
- InstTestRunnerClass: 
- InstTestTargets: 
- UseOrchestrator: false
Uploading app and test files
App path (/bitrise/deploy/Neo.internal-debug-2021.8.apk), is bundle: false
Assets requested: {isBundle:false testApp:<nil> Apk:{UploadURL: GcsPath: Filename:Neo.internal-debug-2021.8.apk} Aab:{UploadURL: GcsPath: Filename:} TestApk:{UploadURL: GcsPath: Filename:app-internal-debug-androidTest.apk} RoboScript:{UploadURL: GcsPath: Filename:} ObbFiles:[]}
Failed to upload test assets, error: failed to start test: 403, error: {"error":"Unauthorized request"}
```

**Comment by ofalvai** [comment] 2021-05-13 06:43
Hey @DanielJette, we looked at your project specifically and made the required fix. Please let us know if it's working now.

**Comment by DanielJette** [comment] 2021-05-13 16:13
Hello @ofalvai . Thank you very much for your attention to this matter. I can confirm that all our workflows are now running correctly.
I appreciate your help with this.

Is there anything regarding this fix that we could have managed on our own? If something similar were to reoccur, what actions should we take?

**Comment by ofalvai** [comment] 2021-05-14 08:03
@DanielJette it was an authentication issue on our side, affecting a certain group of users. We fixed it in an internal system, it was not something a user could have fixed in their workflows. Apologies for the inconvenience caused, and thank you once again for reporting the failure.

**Closed** 2021-07-29 09:36 UTC
