### ISSUE TITLE
Getting weird error: "Failed to get test status: INVALID(DETAILS_UNAVAILABLE)"

### ISSUE THREAD

**Issue by JosefHruska** [bitrise-steplib/steps-virtual-device-testing-for-android#41] opened 2019-03-23 21:46 UTC
Hi,
I am trying to get UI test running on Bitrise but I am getting this weird error right after succesful upload of test APK file to virtual devices. I check if the test works when I run them locally on my PC and it  runs without problem.

Here is the part of the log:

Configs:
- ApkPath: /bitrise/deploy/app-debug-androidTest20190323213124.apk
- TestTimeout: 900
- DirectoriesToPull: /storage/emulated/Pictures/screenshots
- EnvironmentVariables: 
- TestDevices:
---
Model     API Level   Locale     Orientation   
Nexus5X   24          portrait   en            
---
- AppPackageID: app
- TestType: instrumentation
- TestApkPath: /bitrise/deploy/app-debug-androidTest20190323213124.apk
- InstTestPackageID: androidTest
- InstTestRunnerClass: androidx.test.runner.AndroidJUnitRunner
- InstTestTargets: class io.hruska.pocketplay.OnboardingTest
- UseOrchestrator: false
Upload APKs
=> APKs uploaded
Start test
=> Test started
Waiting for test results
- Validating
Failed to get test status, error: Failed to get test status: INVALID(DETAILS_UNAVAILABLE)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | virtual-device-testing-for-android (exit code: 1)             | 12 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...se-steplib/steps-virtual-device-testing-for-android/issues |
| Source: ...thub.com/bitrise-steplib/steps-virtual-device-testing-for-android |
+---+---------------------------------------------------------------+----------+

I also tried to let InstTestPackageID, InstTestRunnerClass and InstTestTargets empty but with no effect.

Here is the link to the build: https://app.bitrise.io/build/60b9c6891b299178

Do you have any idea what should I do?

**Comment by fehersanyi-bitrise** [comment] 2019-03-25 09:39
Hello @JosefHruska!

this error means that the response's status code is not 200 🤔
Could you please enable support user on the app's settings tab so I could check out the setups, and maybe run a few test builds as well?

**Comment by JosefHruska** [comment] 2019-03-25 11:43
@fehersanyi-bitrise 

Thanks for fast reaction.
I just enabled access for you - if you would need any further details just let me know.

**Comment by JosefHruska** [comment] 2019-03-28 12:27
@fehersanyi-bitrise Do we have any update?

**Comment by fehersanyi-bitrise** [comment] 2019-03-28 14:07
@JosefHruska Hy, sorry for the late reply, could you try this?
https://github.com/bitrise-steplib/steps-virtual-device-testing-for-android/issues/17

**Comment by lubos-gelanyi** [comment] 2019-07-31 10:03
Hey Guys, was this ever resolved? I am getting exactly same error. Seems to be caused by providing "DirectoriesToPull". I have tried lots of different paths - always failing on same error. 

In case I keep "DirectoriesToPull" empty everything is working like a charm. However, I need to access test output data
https://app.bitrise.io/build/c6c94a3bdfe7af87

**Comment by hafsalrahman** [comment] 2019-08-05 10:43
Failed to get test status, error: Failed to get test status: INVALID(NO_TEST_RUNNER_CLASS)

**Comment by Roland-Bak** [comment] 2019-08-08 13:52
Hi @hafsalrahman!

Could you try going to your build's workflow and delete the field for 'Test runner class', inside the [Beta] Virtual Device Testing step?
Android Build for UI Testing should take care of this for you, rebuilding with the 'Test runner class' as empty might just do the trick 😉

**Comment by hafsalrahman** [comment] 2019-08-20 13:00
Yea it worked. Thanks @Roland-Bak

**Comment by godrei** [comment] 2019-12-07 15:11
Closing as we did not receive a reply - @JosefHruska please let us know if we can help with anything by opening a new issue!

**Closed by godrei** 2019-12-07 15:11 UTC
